title       = "tiengtrungbotui"
baseURL     = "https://tiengtrungbotui-cli.tamnd.com/"
description = "A command line for tiengtrungbotui."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/tiengtrungbotui-cli"
